export enum RealEstate {
  ApartamentoCasa = 1,
  Moradia,
  EdificioUrbano,
  EstabelecimentoComercial,
  Garagem,
  ConstrucaoTerrenoRustico,
  QuinhaoHereditario,
  DivisaoCoisaComum,
  DireitoAMeacao,
  QuintasHerdades,
  ArrumosArrecadacoes,
  DireitoAHeranca,
  DireitoDeUsufruto,
}
